#!/sbin/busybox sh

if [ "a$2" == "a" ];then
exit
fi

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  exit
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
fi

if [ "$bass_boost_effect" == "0" ];then
  echo 0 > /sys/class/misc/scoobydoo_sound/digital_gain
  echo 0 > /sys/class/misc/scoobydoo_sound/headphone_eq
  exit
fi

d=-`expr $bass_boost_gain \* 1000 \* $dynamic_range \/ 100`
echo $d > /sys/class/misc/scoobydoo_sound/digital_gain

case "$bass_boost_effect" in
  1)
    echo 1 A 0x0FF3 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 B 0x03F2 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 PG 0x0034 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo $bass_boost_gain > /sys/class/misc/scoobydoo_sound/headphone_eq_b1_gain
    echo 0 > /sys/class/misc/scoobydoo_sound/headphone_eq_b2_gain
    echo 1 > /sys/class/misc/scoobydoo_sound/headphone_eq
    ;;
  2)
    echo 1 A 0x0FE3 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 B 0x0403 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 PG 0x0074 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo $bass_boost_gain > /sys/class/misc/scoobydoo_sound/headphone_eq_b1_gain
    echo 0 > /sys/class/misc/scoobydoo_sound/headphone_eq_b2_gain
    echo 1 > /sys/class/misc/scoobydoo_sound/headphone_eq
    ;;
  3)
    echo 1 A 0x0FBB > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 B 0x0407 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 PG 0x0114 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo $bass_boost_gain > /sys/class/misc/scoobydoo_sound/headphone_eq_b1_gain
    echo 0 > /sys/class/misc/scoobydoo_sound/headphone_eq_b2_gain
    echo 1 > /sys/class/misc/scoobydoo_sound/headphone_eq
    ;;
  4)
    echo 1 A 0x0FBB > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 B 0x0407 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 1 PG 0x0114 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 2 A 0x1F8C > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 2 B 0xF073 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 2 C 0x040A > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo 2 PG 0x01C8 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
    echo -$bass_boost_gain > /sys/class/misc/scoobydoo_sound/headphone_eq_b1_gain
    echo $bass_boost_gain > /sys/class/misc/scoobydoo_sound/headphone_eq_b2_gain
    echo 1 > /sys/class/misc/scoobydoo_sound/headphone_eq
    ;;
esac;
 

