#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  case "$2" in
    on)
      echo 1 > /data/media/.nobootlogo
      ;;
    off)
      rm -f /data/media/.nobootlogo
      ;;
  esac;
fi

if [ -f /data/media/.nobootlogo ];then
  echo on
else
  echo off
fi
