#!/sbin/busybox sh
cd /

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys
tar xvf /res/misc/dev.tar

if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  echo 0 > /proc/sys/kernel/rom_feature_set
  cp -a /res/misc/init.40/* /
  cp lpm.rc init.rc
  rm init.smdk4x12.rc
  exec /sbin/init2
fi

mkdir -p /dev/block
mknod /dev/block/mmcblk0p9 b 179 9
mount -t ext4 /dev/block/mmcblk0p9 /system

AOSP=0
MIUI=0
CM10=0
JB=0

[ -f /system/framework/framework2.jar ] || AOSP=1
[ -f /system/framework/miui-framework.jar ] && MIUI=1
[ -f /system/lib/ssl/engines/libkeystore.so ] && JB=1
[ -f /system/framework/seccamera.jar ] || CM10=1

if [ "$JB" == 1 ];
then
  mv -f /sbin/adbd.jb /sbin/adbd
  if [ "$CM10" == 1 ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.cm10/* /
  else
    echo 0 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.41/* /
  fi
else
  if [ "$AOSP" == "1" ];
  then
    echo 1 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.cm9/* /
  else
    echo 0 > /proc/sys/kernel/rom_feature_set
    mv -f /res/misc/init.40/* /
  fi;
fi

if [ "$SECONDROM" == "1" ];then
  mv /init.smdk4x12.rc.2 /init.smdk4x12.rc
  mv /init.rc.2 /init.rc
else
  rm -f /init.rc.2 /init.smdk4x12.rc.2
fi

umount /system
rm -rf /res/misc/init*
chmod 755 /innt
chmod 644 /*.rc
chmod 644 /*.prop
exec /sbin/init2

